name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@ec2-34-229-16-6.compute-1.amazonaws.com:PLAYGREEN-Sports

      - name: Restart PM2 on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-34-229-16-6.compute-1.amazonaws.com << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd PLAYGREEN-Sports
            npm install
            npm run build
            pm2 restart PLAYGREEN-Sports || pm2 start npm --name "PLAYGREEN-Sports" -- run start
          EOF
